### ISSUE TITLE
[Bug]:  When the file extension is *.FBX, the file cannot be imported.

### ISSUE THREAD

**Issue by iloveyehan** [mika-f/blender-drag-and-drop#71]
### What happened?

A bug happened!

### Add-on Version

2.12.0

**Comment by mika-f** [comment]
What version of Blender are you using?
If you use Blender 4.0.1 (latest version), this add-on does not support it.

**Comment by iloveyehan** [comment]
i use 4.0.0

**Comment by iloveyehan** [comment]
Changing the file name to *.fbx should allow for import, it seems to be an issue with case sensitivity

**Comment by mika-f** [comment]
Thank you for more information. A fix will be released as v2.12.1 soon.

**Comment by mika-f** [comment]
Fixed in [v2.12.1](https://github.com/mika-f/blender-drag-and-drop/releases/tag/v2.12.1)

**Comment by carmo2011** [comment]
> Fixed in [v2.12.1](https://github.com/mika-f/blender-drag-and-drop/releases/tag/v2.12.1)
still not work for me
blender 4.0.2 chinese, addon 2.12.1
no any response when drag .fbx

**Comment by mika-f** [comment]
v2.12.1 does not supports Blender 4.0.2. Please use latest **alpha** release.
